### Create user
POST http://localhost:3001/users/signup
Content-Type: application/json

{
    "userid": "",
    "username": "",
    "email": "",
    "password": ""
}

### Login user 
GET http://localhost:3001/users/Login
Content-Type: application/json

{
    "email": "",
    "password": ""
}

### Get userid from email
GET http://localhost:3001/users/getid
Content-Type: application/json

{
    "email": "abe@mail.com"
}

### Update user email from userid
PUT http://localhost:3001/users/updateemail
Content-Type: application/json

{
    "userid": "",
    "email": ""
}

### Update user password from userid
PUT http://localhost:3001/users/updatepwd
Content-Type: application/json

{
    "userid": "1",
    "password": "password"
}

### Add a debit card to a userid
POST http://localhost:3001/debit/add
Content-Type: application/json

{
    "userid": "",
    "cardid": "",
    "debitid": "",
    "cardname": "",
    "available": ""
}

### Add a credit card to a userid
POST http://localhost:3001/credit/add
Content-Type: application/json

{
    "userid": "",
    "cardid": "",
    "creditid": "",
    "cardname": "",
    "outstanding": "",
    "lineofcredit": ""
}

### Get a user's cards from userid
GET http://localhost:3001/cards/get
Content-Type: application/json

{
    "userid": ""
}

### Delete a debit card from debitid
DELETE http://localhost:3001/debit/delete
Content-Type: application/json

{
    "debitid": ""
}

### Delete a credit card from creditid
DELETE http://localhost:3001/credit/delete
Content-Type: application/json

{
    "creditid": ""
}


### Add a budget to userid
POST http://localhost:3001/budget/add
Content-Type: application/json

{
    "userid": "",
    "budgetid": "",
    "amount": "",
    "days": ""
}

### Get budget from userid
GET http://localhost:3001/budget/get
Content-Type: application/json

{
    "userid": ""
}

### Update budget from budgetid
PUT http://localhost:3001/budget/update
Content-Type: application/json

{
    "userid": "",
    "budgetid": "",
    "update": "",
    "amount": "",
    "days": ""
}

### Delete a budget from budgetid
DELETE http://localhost:3001/budget/delete
Content-Type: application/json

{
    "budgetid": ""
}

### Add cycle to userid
POST http://localhost:3001/cycles/add
Content-Type: application/json

{
    "userid": "",
    "cycleid": "",
    "balance": "",
    "begindate": "",
    "enddate": ""
}

### Get current cycle from userid
GET http://localhost:3001/cycles/get
Content-Type: application/json

{
    "userid": ""
}

### Add purchase to userid
POST http://localhost:3001/purchases/add
Content-Type: application/json

{
    "cycleid": "",
    "debitid": "",
    "creditid": "",
    "purchaseid": "",
    "title": "",
    "description": "",
    "amount": "",
    "date": ""
}

### Get purchases of current cycle from userid
GET http://localhost:3001/purchases/get
Content-Type: application/json

{
    "userid": ""
}

### Delete purchase from userid
DELETE http://localhost:3001/purchases/delete
Content-Type: application/json

{
    "purchaseid": ""
}