###  Create User
POST http://localhost:3001/signup
Content-Type: application/json

{
    "userid": "10",
    "username": "new",
    "email": "10@test.com",
    "password": "pwd"
}

### Login User
POST http://localhost:3001/login
Content-Type: application/json

{
    "email": "new@mail.com",
    "password": "password"
}

### Get userid from email
GET http://localhost:3001/userid
Content-Type: application/json

{
    "email": "shae@mail.com"
}

### Update email from userid
PUT http://localhost:3001/users/emailupdate
Content-Type: application/json

{
    "userid": "1",
    "email": "new@mail.com"
}

### Update password from userid
PUT http://localhost:3001/users/pwdupdate
Content-Type: application/json

{
    "userid": "5",
    "password": "password"
}

### Get users cards from userid
GET http://localhost:3001/usercards
Content-Type: application/json

{
    "userid": "1"
}

### Get the current cycle from userid
GET http://localhost:3001/cycle
Content-Type: application/json

{
    "userid": "1"
}

### Get purchases of current cycle from userid
GET http://localhost:3001/purchases
Content-Type: application/json

{
    "userid": "1"
}






# ### TEMP
# POST http://localhost:3001/test
